### ISSUE TITLE
new code structure based in folder-by-features

### ISSUE THREAD

**Issue by Tsugami** [MenheraBot/MenheraBot#108]
https://softwareengineering.stackexchange.com/questions/338597/folder-by-type-or-folder-by-feature

**Comment by Tsugami** [comment]
I was thinking about:
```
- modules <- features folder
  - guild 
     - events
     - commands
     - GuildModal.ts
     - GuildController.ts
```

**Comment by ySnoopyDogy** [comment]
What if separate events and commands from this, like

```
- modules
      - guild
            - GuildModal
            - GuildRepository
      - bot
             - events
             - commands
       - user
             - UserModal
             - UserRepo
             ```

Its a good idea, but i dont know like where to put topRepository, relationshipRepository, localeStructure, eventManager, rpgHanfdler, ProfileBadges...

This are some of the examples that i can't think to place in this folder structure

**Comment by Tsugami** [comment]
why events and commands in own local? I don't think folder for just two files makes sense, everything is about the bot in end. must have some app that we can visually organize this and see the final result
