### ISSUE TITLE
[FEATURE] Add TSDOC

### ISSUE THREAD

**Issue by LordLucass** [MenheraBot/MenheraBot#222]
Add the [TSDOC](https://tsdoc.org/) to the application codes.

Why? TSDoc makes it easier for programmers who are willing to contribute to the application, both internally and externally, to understand it. Because of this, it is recommended to maintain good readability and conciseness about functions by explaining in detail and briefly their function, their respective parameters and their return.

**Comment by ySnoopyDogy** [comment]
I am not sure about it. I mean, this is a tiny project, that I do for fun. I think that adding this would lead for a lot of exrta job to write the definitions to all existing functions. TS gives some type safety that help when coding

**Comment by LordLucass** [comment]
In fact, it would be a lot of work, but there would be benefits at other points, however, this is optional and you decide, if you believe that currently it is not necessary to implement this kind of concept in it, okay.
