### ISSUE TITLE
Understand why is Menhera using so much memory

### ISSUE THREAD

**Issue by ySnoopyDogy** [MenheraBot/MenheraBot#246]
With the beta process running, we could identify that Menhera is using 80MB more memory than when it starts.

Beta has less users, and less commands being used.

![image](https://github.com/MenheraBot/MenheraBot/assets/59155752/fda1150d-8cb5-480b-a404-70308baac872)

**Comment by LordLucass** [comment]
# Warn
*So far, these are the reservations I have to make, but as the code is observed, I will try to edit this message with new information. This is just for information so far, there is no definitive statement, as everything is done by eye in theory, nothing very practical.*


**During an inspection of Menhera's source code, I noticed that from the `rest` folder to the `orchestrator` folder there are no obvious memory leaks, however, there are some situations where it is worth keeping an eye on, as they can have a significant impact on the application's performance in certain contexts.**

- [packages/orchestrator/src/prometheusWorkarround.ts](https://github.com/MenheraBot/MenheraBot/blob/beta/packages/orchestrator/src/prometheusWorkarround.ts) - It's worth noting that efficiency and performance can depend on the size of the input data. If the size of the input data (for example, the metrics) is very large, it can be useful to optimize string manipulation to avoid consuming too much memory.

**Comment by ySnoopyDogy** [comment]
Thanks for your support on this @Guaranisgk and sorry for the late response.

The metrics can be a problem in the future if i continue to add more and more metrics. I'll think a better way of doing this in the future. At the moment, it's ok to leave things as they are, given the low number of metrics that currently exist.

# Today

I found a bug that is probably the main actor for the memory usage. 

I'm not sure why, but my library is blocking requests in the rate limits handling system.

I received an alert of memory usage, and in the same moment, the rate limit system had 2 blocked queues:

![image](https://github.com/MenheraBot/MenheraBot/assets/59155752/86390345-57de-4519-9737-fbf7b26b2786)
![image](https://github.com/MenheraBot/MenheraBot/assets/59155752/bc042433-ae49-48e8-bfc0-7952b362dc21)

For some reason the "remaining" and "max" stays at 0 and 1, and because timeoutId is 0, i assume that the loop that checks the rate limits were not running, even that processing was true. With that "isRequestAllowed" were always false, blocking the request from being made in the [waitUntilRequestAvailable](https://github.com/discordeno/discordeno/blob/18.0.1/rest/createQueueBucket.ts#L31) promise.

This also happens in the https://discord.com/api/v10/users/@me/channels route:
![image](https://github.com/MenheraBot/MenheraBot/assets/59155752/e4692c81-d97b-4d25-80ba-07cf7bf8baa5)

To release the requests from being made, i just settled `remaining` to 1, and all requests were flushed with the real rate limit headers being set as the `max` and `remaining`:

![image](https://github.com/MenheraBot/MenheraBot/assets/59155752/2d356d8b-5709-4c1b-9dbc-d8f69037f7cb)

Disordeno is a few steps away from releasing v19 https://github.com/discordeno/discordeno/issues/3270, so I imagine they won't take the time to see a fix for this. I'm going to wait for this release and migrate the bot completely to it.

Until then, I'm going to do the famous enjambre to free up stuck queues
